import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P as PressStart2PFont } from "next/font/google";
import "./globals.css";
import "nes.css/css/nes.min.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

const pressStart2P = PressStart2PFont({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-press-start-2p",
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
